<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Estadística Descriptiva</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Inicio</a>
</li>
<li>
  <a href="Ayuda.html">¿Cómo utilizar estos apuntes?</a>
</li>
<li>
  <a href="GitHub_en_RStudio.html">Git y GitHub en RStudio</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Contenido
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Unidades</li>
    <li>
      <a href="U1.html">Unidad 1</a>
    </li>
    <li>
      <a href="U2.html">Unidad 2</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Estadística Descriptiva</h1>

</div>


<p>Los métodos estadísticos son muy importantes, ya que ellos nos permiten conocer los fenómenos que nos rodean, en aspectos que quizá no nos imaginamos. Por doquier estamos expuestos a los <strong>datos</strong>, y eso se extiende a científicos e ingenieros en sus actividades profesionales.<br />
Es muy importante definir los objetos que se constituyen en una <strong>población</strong> de interés. Dicha población puede ser el conjunto de todos los productos elaborados en una fábrica un día determinado, o todos los estudiantes egresados de cierta carrera en la generación 2017, por ejemplo. Cuando tenemos acceso a todos los datos deseados de todos los miembros de una población, tenemos un <strong>censo</strong>.<br />
Sin embargo, es muy complicado poder realizar censos, ya sea por escasez de tiempo o de dinero. Por ello, se prefiere seleccionar un grupo pequeño de elementos de la población de manera aleatoria, para tener lo que se conoce como una <strong>muestra</strong>.<br />
Cabe mencionar que en ocasiones, no nos interesan todas las características de los objetos de una población. Por ejemplo, puede que hayamos reunido a 50 personas para analizar su estado de salud. Probablemente debamos preguntarles su edad, su peso, su estatura y tomarles medidas de su temperatura o presión arterial; sin embargo, no tiene sentido preguntarles qué equipo de futbol es su favorito o a qué hora pasan su noticiero predilecto. Lo que necesitamos son sus características.<br />
A las características podemos dividirlas en dos: <strong>categóricas</strong> y <strong>numéricas</strong>. Las primeras son etiquetas, como los nombres o la marca de un coche. Las segundas pueden expresarse con números. Definamos una <strong>variable</strong> como cualquier característica cuyo valor puede cambiar de un sujeto a otro.</p>
<div id="ramas-de-la-estadistica" class="section level2">
<h2>Ramas de la Estadística</h2>
<p>Dividiremos la Estadística en dos ramas por el momento. En primera instancia, es necesario recopilar, organizar, resumir y presentar los datos; de esto se encarga la <strong>Estadística Descriptiva</strong>. Por otro lado, se desea extender las propiedades de la muestra hacia la población, mediante inferencias que permitan comprender mejor su comportamiento e incluso pronosticarlo; esa es la función de la <strong>Estadística Inferencial</strong>.</p>
</div>
<div id="estadistica-descriptiva-en-accion" class="section level2">
<h2>Estadística Descriptiva en acción</h2>
<p>La tragedia que sufrió el transbordador espacial Challenger y sus astronautas en 1986 condujo a varios estudios para investigar las razones de la falla de la misión. La atención se enfocó de inmediato en el comportamiento de los sellos anulares del motor del cohete. He aquí datos derivados de observaciones en x = temperatura del sello anular (°F) en cada encendido de prueba o lanzamiento del motor del cohete del transbordador (Presidential Commission on the Space Shuttle Challenger Accident, Vol. 1, 1986: 129-131). Los datos se presentan en una sola columna para dejar en claro que se refieren a datos univariables. Cabe mencionar que los datos se encuentran en la carpeta <em>datasets</em> del repositorio de la asignatura en <a href="https://github.com/LuisEMendoza/RMarkdown-test/tree/master/datasets">GitHub</a>.</p>
<pre><code>##  [1] 84 49 61 40 83 67 45 66 70 69 80 58 68 60 67 72 73 70 57 63 70 78 52
## [24] 67 53 67 75 61 70 81 76 79 75 76 58 31</code></pre>
<p>A simple vista, los datos así mostrados no dicen gran cosa. Para ello es deseable organizarlos de manera que muestren algún comportamiento en particular. Una de las maneras más burdas es el <strong>diagrama de tallo y hojas</strong>, el cual se muestra a continuación:</p>
<pre><code>## 
##   The decimal point is 1 digit(s) to the right of the |
## 
##   3 | 1
##   4 | 059
##   5 | 23788
##   6 | 01136777789
##   7 | 000023556689
##   8 | 0134</code></pre>
<p>La explicación del diagrama es sencilla: las cifras que representan las decenas se colocan como tallos, mientras que las cifras que son unidades se vuelven hojas. Este diagrama nos permite saber de manera rápida cuáles son las temperaturas más comunes o frecuentes en nuestro conjunto de datos. También puede decirse que es un <strong>histograma</strong> muy rudimentario.</p>
<p>A continuación se muestra un histograma:</p>
<p><img src="U1_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Y para terminar, una gráfica que posteriormente se verá cómo interpretarse y construirse es la <strong>gráfica de caja</strong>, la cual se muestra a continuación:</p>
<p><img src="U1_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Lo anterior, así como la tabla donde se muestran los datos, fue realizado con un <em>software</em> estadístico: <strong>R</strong>.</p>
</div>
<div id="representaciones-graficas-y-tabulares" class="section level2">
<h2>Representaciones gráficas y tabulares</h2>
<p>Es importante mencionar que existe una notación que debemos considerar: el número de observaciones presentes en un conjunto de datos dado, se denotará por la letra <em>n</em>. También, cada observación se denotará por la letra <em>x</em> acompañada de un subíndice que no tiene ninguna función más que identificar los datos. Es decir, representar una observación como <span class="math inline">\(x_1\)</span> no implica que esta sea la más pequeña. Con esto en mente, pasamos a revisar las representaciones gráficas de los datos.</p>
<div id="diagrama-de-tallo-y-hojas" class="section level3">
<h3>Diagrama de tallo y hojas</h3>
<p>Anteriormente se habló un poco de este diagrama. Es bastante sencillo y puede aplicarse a números decimales. Veamos los pasos para producirlos:</p>
<ol style="list-style-type: decimal">
<li>Se selecciona uno o más de los primeros dígitos para el tallo. Los dígitos restantes serán las hojas.</li>
<li>Los valores del tallo se escriben de manera vertical.</li>
<li>Se anota una hoja por cada observación a la derecha del tallo.</li>
<li>Se indican las unidades para tallos y hojas en algún lugar de la gráfica.</li>
</ol>
<p>Una gráfica de tallos y hojas da información sobre los siguientes aspectos de los datos: - Identificación de un valor típico o representativo. - Grado de dispersión en torno al valor típico. - Presencia de brechas en los datos. - Grado de simetría en la distribución de los valores. - Número y localización de crestas. - Presencia de valores afuera de la gráfica.</p>
<p>A modo de práctica, tomemos los siguientes valores que representan el flujo de agua en regaderas de Australia en litros por minuto, para <em>n = 130</em>. Se muestra también el código en <em>R</em> para mostrar y calcular el diagrama:</p>
<pre class="r"><code>flujo &lt;- scan(&quot;datasets/002-flujo.txt&quot;)
flujo</code></pre>
<pre><code>##   [1]  4.6 12.3  7.1  7.0  4.0  9.2  6.7  6.9 11.5  5.1 11.2 10.5 14.3  8.0
##  [15]  8.8  6.4  5.1  5.6  9.6  7.5  7.5  6.2  5.8  2.3  3.4 10.4  9.8  6.6
##  [29]  3.7  6.4  8.3  6.5  7.6  9.3  9.2  7.3  5.0  6.3 13.8  6.2  5.4  4.8
##  [43]  7.5  6.0  6.9 10.8  7.5  6.6  5.0  3.3  7.6  3.9 11.9  2.2 15.0  7.2
##  [57]  6.1 15.3 18.9  7.2  5.4  5.5  4.3  9.0 12.7 11.3  7.4  5.0  3.5  8.2
##  [71]  8.4  7.3 10.3 11.9  6.0  5.6  9.5  9.3 10.4  9.7  5.1  6.7 10.2  6.2
##  [85]  8.4  7.0  4.8  5.6 10.5 14.6 10.8 15.5  7.5  6.4  3.4  5.5  6.6  5.9
##  [99] 15.0  9.6  7.8  7.0  6.9  4.1  3.6 11.9  3.7  5.7  6.8 11.3  9.3  9.6
## [113] 10.4  9.3  6.9  9.8  9.1 10.6  4.5  6.2  8.3  3.2  4.9  5.0  6.0  8.2
## [127]  6.3  3.8  6.0  8.3</code></pre>
<p>Construyamos nuestro diagrama:</p>
<pre class="r"><code>stem(flujo)</code></pre>
<pre><code>## 
##   The decimal point is at the |
## 
##    2 | 23
##    3 | 2344567789
##    4 | 01356889
##    5 | 00001114455666789
##    6 | 0000122223344456667789999
##    7 | 00012233455555668
##    8 | 022333448
##    9 | 012233335666788
##   10 | 2344455688
##   11 | 2335999
##   12 | 37
##   13 | 8
##   14 | 36
##   15 | 0035
##   16 | 
##   17 | 
##   18 | 9</code></pre>
<ul>
<li>¿Cuál es una velocidad de flujo o gasto típico o representativo?</li>
<li>¿Parece estar la gráfica altamente concentrada o dispersa?</li>
<li>¿Es la distribución de valores razonablemente simétrica? Si no, ¿cómo describiría el alejamiento de la simetría?</li>
<li>¿Describiría cualquier observación como alejada del resto de los datos (un valor extremo)?</li>
</ul>
</div>
<div id="diagrama-de-puntos" class="section level3">
<h3>Diagrama de puntos</h3>
<p>Es un resumen atractivo de datos numéricos cuando el conjunto es razonablemente pequeño o existen pocos valores de datos distintos. Cada observación está representada por un punto sobre la ubicación correspondiente en una escala de medición horizontal. Cuando un valor ocurre más de una vez, existe un punto por cada ocurrencia y estos puntos se apilan verticalmente. Como con la gráfica de tallos y hojas, una gráfica de puntos da información sobre la localización, dispersión, extremos y brechas. Usemos como ejemplo el conjunto de las temperaturas del <em>Challenger</em>.</p>
<pre class="r"><code>stripchart(temp, method = &#39;stack&#39;)</code></pre>
<p><img src="U1_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="tablas-de-frecuencia" class="section level3">
<h3>Tablas de frecuencia</h3>
<p>Vamos a trabajar ahora con datos categóricos. Cuando hablamos de categorías, hablamos de variables nominales, es decir, nombres o etiquetas. Por lo tanto, el tratamiento que debemos darles difiere de los números. Por principio de cuentas, debemos tabularlos. Esto se consigue con una tabla de frecuencias. Primero leemos el archivo con los datos:</p>
<pre class="r"><code>marca &lt;- c(read.table(&quot;datasets/003-marca.txt&quot;))
marca</code></pre>
<pre><code>## $V1
##  [1] Apple    Apple    Samsung  HTC      Apple    Xiaomi   Nokia   
##  [8] Samsung  Motorola Samsung  Samsung  Apple    Apple    Huawei  
## [15] Motorola Samsung  Samsung  Apple    Motorola Nokia    Huawei  
## [22] Huawei   Motorola Samsung  Samsung  Apple    Samsung  LG      
## [29] Apple    Samsung  Motorola Huawei  
## Levels: Apple HTC Huawei LG Motorola Nokia Samsung Xiaomi</code></pre>
<p>Construir una tabla de frecuencias implica contar el número de veces que una etiqueta se repite. A esa cantidad se le conoce como la frecuencia absoluta. Enseguida creamos la tabla:</p>
<pre class="r"><code>mar &lt;- table(marca)
mar</code></pre>
<pre><code>## marca
##    Apple      HTC   Huawei       LG Motorola    Nokia  Samsung   Xiaomi 
##        8        1        4        1        5        2       10        1</code></pre>
<p>De aquí en delante podemos complementar la tabla de frecuencias agregando la frecuencia acumulada y la relativa. Llenémosla:</p>
<table>
<thead>
<tr class="header">
<th align="left">Marca</th>
<th align="center">Frecuencia</th>
<th align="center">Frec. acumulada</th>
<th align="center">Frec. relativa</th>
<th align="center">Frec. rel. acumulada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Apple</td>
<td align="center">8</td>
<td align="center">8</td>
<td align="center">0.25</td>
<td align="center">0.25</td>
</tr>
<tr class="even">
<td align="left">HTC</td>
<td align="center">1</td>
<td align="center">9</td>
<td align="center">0.03125</td>
<td align="center">0.28125</td>
</tr>
<tr class="odd">
<td align="left">Huawei</td>
<td align="center">4</td>
<td align="center">13</td>
<td align="center">0.125</td>
<td align="center">0.40625</td>
</tr>
<tr class="even">
<td align="left">LG</td>
<td align="center">1</td>
<td align="center">14</td>
<td align="center">0.03125</td>
<td align="center">0.4375</td>
</tr>
<tr class="odd">
<td align="left">Motorola</td>
<td align="center">5</td>
<td align="center">19</td>
<td align="center">0.15625</td>
<td align="center">0.59375</td>
</tr>
<tr class="even">
<td align="left">Nokia</td>
<td align="center">2</td>
<td align="center">21</td>
<td align="center">0.0625</td>
<td align="center">0.65625</td>
</tr>
<tr class="odd">
<td align="left">Samsung</td>
<td align="center">10</td>
<td align="center">31</td>
<td align="center">0.3125</td>
<td align="center">0.96875</td>
</tr>
<tr class="even">
<td align="left">Xiaomi</td>
<td align="center">1</td>
<td align="center">32</td>
<td align="center">0.03125</td>
<td align="center">1</td>
</tr>
</tbody>
</table>
<p>La frecuencia acumulada, también conocida como frecuencia absoluta acumulada, se corresponde con la suma de las frecuencias que han aparecido hasta el momento. Por ejemplo, la frecuencia acumulada para Huawei es de 13, que se corresponde con los 8 de Apple, la única de HTC y las 4 unidades de la propia Huawei. La frecuencia relativa es el cociente de la frecuencia absoluta entre el total de observaciones, por ejemplo, para Apple se corresponde con el resultado de dividir sus 8 unidades entre el total, que fueron 32. Esos cocientes se acumulan para obtener la frecuencia relativa acumulada.</p>
<p>Ahora bien, la única ocasión en la que se recomienda utilizar un diagrama de sectores -también conocido como de pastel-, es cuando se trabaja con variables nominales (etiquetas o categorías). Para su construcción, basta con tomar la frecuencia relativa de cada categoría y multiplicarla por 360, que son la totalidad de los grados contenidos en un círculo completo.</p>
<table>
<thead>
<tr class="header">
<th align="left">Marca</th>
<th align="center">Grados</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Apple</td>
<td align="center">90</td>
</tr>
<tr class="even">
<td align="left">HTC</td>
<td align="center">11.25</td>
</tr>
<tr class="odd">
<td align="left">Huawei</td>
<td align="center">45</td>
</tr>
<tr class="even">
<td align="left">LG</td>
<td align="center">11.25</td>
</tr>
<tr class="odd">
<td align="left">Motorola</td>
<td align="center">56.25</td>
</tr>
<tr class="even">
<td align="left">Nokia</td>
<td align="center">22.5</td>
</tr>
<tr class="odd">
<td align="left">Samsung</td>
<td align="center">112.5</td>
</tr>
<tr class="even">
<td align="left">Xiaomi</td>
<td align="center">11.25</td>
</tr>
</tbody>
</table>
<p>El círculo se divide en las 8 secciones con magnitudes en grados ya calculadas. El diagrama quedaría de la siguiente manera (elaborada con R):</p>
<pre class="r"><code>pie(mar)</code></pre>
<p><img src="U1_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="distribuciones-de-frecuencia" class="section level3">
<h3>Distribuciones de frecuencia</h3>
<p>En ocasiones es necesario trabajar con valores que no se repiten tanto, como en el caso que se presenta enseguida.</p>
<p>Las compañías eléctricas requieren información sobre el consumo de los clientes para obtener pronósticos precisos de demandas. Investigadores de Wisconsin Power and Light determinaron el consumo de energía (BTU) durante un periodo particular con una muestra de 90 hogares calentados con gas. Las siguientes observaciones son el consumo promedio:</p>
<pre class="r"><code>Consumo &lt;- scan(&quot;datasets/004-horno.txt&quot;)
Consumo</code></pre>
<pre><code>##  [1]  2.97  4.00  5.20  5.56  5.94  5.98  6.35  6.62  6.72  6.78  6.80
## [12]  6.85  6.94  7.15  7.16  7.23  7.29  7.62  7.62  7.69  7.73  7.87
## [23]  7.93  8.00  8.26  8.29  8.37  8.47  8.54  8.58  8.61  8.67  8.69
## [34]  8.81  9.07  9.27  9.37  9.43  9.52  9.58  9.60  9.76  9.82  9.83
## [45]  9.83  9.84  9.96 10.04 10.21 10.28 10.28 10.30 10.35 10.36 10.40
## [56] 10.49 10.50 10.64 10.95 11.09 11.12 11.21 11.29 11.43 11.62 11.70
## [67] 11.70 12.16 12.19 12.28 12.31 12.62 12.69 12.71 12.91 12.92 13.11
## [78] 13.38 13.42 13.43 13.47 13.60 13.96 14.24 14.35 15.12 15.24 16.06
## [89] 16.90 18.26</code></pre>
<p>Es notorio que los valores son bastantes y que rara vez se repiten. Cuando nuestros datos son así, se recomienda agruparlos en una distribución de frecuencias. Dicha distribución divide los datos en intervalos y cuenta las ocasiones en que los mismos datos se encuentran entre estos intervalos. A estos últimos se les conoce también como <strong>clases</strong>.</p>
<p>El primer paso es determinar el número de datos. En esta ocasión ya lo sabemos, son 90. Si en un momento dado no fuera así, podemos contarlos con el siguiente comando:</p>
<pre class="r"><code>n &lt;- length(Consumo)
n</code></pre>
<pre><code>## [1] 90</code></pre>
<p>Entonces toca definir el número de clases. No existe una regla inamovible para hacer esto, pero usualmente se utiliza uno de los tres criterios siguientes:</p>
<p><strong>La raíz cuadrada del número de datos</strong>. Al momento de contar el total de observaciones, se calcula la raíz de dicho valor. <span class="math display">\[
total\ de\ clases \ \approx \sqrt {total\ de\ observaciones}
\]</span></p>
<pre class="r"><code>sqrt(n)</code></pre>
<pre><code>## [1] 9.486833</code></pre>
<p>Redondeamos hacia arriba y definimos el número de clases como diez.</p>
<p><strong>La Regla de Sturges</strong>. Fue propuesta en 1926 y es la que utilizan en su mayoría los programas estadísticos para el cálculo y elaboración de histogramas y distribuciones de frecuencia. Su fórmula es:</p>
<p><span class="math display">\[
k=1+log_2(n)
\]</span> Donde <span class="math inline">\(k\)</span> es el número de clases y <span class="math inline">\(n\)</span> es el tamaño de muestra. Para este caso, el número de clases sería:</p>
<pre class="r"><code>ksturges &lt;- 1+log2(n)
ksturges</code></pre>
<pre><code>## [1] 7.491853</code></pre>
<p><strong>La regla de Scott</strong>. Propuesta en 1992, utiliza la distribución normal como base y recomienda utilizar la expresión:</p>
<p><span class="math display">\[
k=(2n)^{1/3}
\]</span></p>
<pre class="r"><code>kscott &lt;- (2*n)^(1/3)
kscott</code></pre>
<pre><code>## [1] 5.646216</code></pre>
<p>Con el número de clases ya definido, lo siguiente en realizar será determinar la anchura o límites de la clase. Igual que en el número de clases, no existe una regla infalible para hacerlo, y muchas veces puede dejarse a criterio de la persona que realiza el análisis. Se pueden mencionar dos pautas:</p>
<p><strong>Al tanteo</strong>. En este caso obtenemos el número más bajo y el más alto y buscamos unos límites que nos permitan englobar dichos números sin que quepa la posibilidad de dejar algún valor fuera. Por ejemplo, el número más bajo (o mínimo) es <span class="math inline">\(2.97\)</span>, por lo cual podríamos definir <span class="math inline">\(2.5\)</span> o incluso <span class="math inline">\(2\)</span> como límite inferior de la primera clase; en el otro extremo, el valor máximo es <span class="math inline">\(18.26\)</span>, por lo que podremos dejar <span class="math inline">\(18.5\)</span>, <span class="math inline">\(19\)</span> o incluso <span class="math inline">\(20\)</span> como límite superior. Cabe mencionar que el <span class="math inline">\(20\)</span> sería para asegurarnos de tener clases «simétricas».</p>
<p><strong>Por fórmula</strong>. En este caso, prescindimos de estar buscando un número adecuado y lo calculamos directamente con la siguiente expresión:</p>
<p><span class="math display">\[
Anchura=\frac {R}{NC}
\]</span> Donde <span class="math inline">\(R\)</span> es el rango (esto es, la diferencia entre el valor máximo y el mínimo) y <span class="math inline">\(NC\)</span> es el número de clases. Supongamos que queremos 9 clases, entonces encontremos el máximo y el mínimo:</p>
<pre class="r"><code>max(Consumo)</code></pre>
<pre><code>## [1] 18.26</code></pre>
<pre class="r"><code>min(Consumo)</code></pre>
<pre><code>## [1] 2.97</code></pre>
<p>Y ahora calculamos la anchura:</p>
<pre class="r"><code>anchura &lt;- (max(Consumo)-min(Consumo))/9
anchura</code></pre>
<pre><code>## [1] 1.698889</code></pre>
<p>Al ser un valor decimal, se recomienda redondearse hacia arriba, quedando en dos. Así que nuestras clases comenzarían en 2 como límite inferior, y aumentarán de dos en dos hasta alcanzar el límite superior: 20.</p>
<p>Podríamos graficar el histograma directamente, pero queremos obtener la distribución de frecuencias también. Para ello, ejecutamos la función <code>hist</code> pero con la opción de no mostrarlo y con el número de clases que hayamos definido.</p>
<pre class="r"><code>df &lt;- hist(Consumo, nclass = 9, plot = FALSE, right = FALSE)
df</code></pre>
<pre><code>## $breaks
##  [1]  2  4  6  8 10 12 14 16 18 20
## 
## $counts
## [1]  1  5 17 24 20 16  4  2  1
## 
## $density
## [1] 0.005555556 0.027777778 0.094444444 0.133333333 0.111111111 0.088888889
## [7] 0.022222222 0.011111111 0.005555556
## 
## $mids
## [1]  3  5  7  9 11 13 15 17 19
## 
## $xname
## [1] &quot;Consumo&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;</code></pre>
<pre class="r"><code>intervalos &lt;- df$breaks
clases &lt;- cut(Consumo, breaks = intervalos, dig.lab = 2, right = FALSE)
tabla.frec &lt;- table(clases)
tabla &lt;- as.data.frame(tabla.frec)
tabla</code></pre>
<pre><code>##    clases Freq
## 1   [2,4)    1
## 2   [4,6)    5
## 3   [6,8)   17
## 4  [8,10)   24
## 5 [10,12)   20
## 6 [12,14)   16
## 7 [14,16)    4
## 8 [16,18)    2
## 9 [18,20)    1</code></pre>
<p>El histograma quedaría así:</p>
<pre class="r"><code>hist(Consumo, right = FALSE)</code></pre>
<p><img src="U1_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
<div id="histograma-con-anchos-de-clase-desiguales" class="section level3">
<h3>Histograma con anchos de clase desiguales</h3>
<p>Es posible que las clases de ancho-igual no sean una opción sensible si un conjunto de datos “se alarga” hacia un lado o el otro. Como ejemplo, veamos el siguiente caso:</p>
<p>En un estudio de ruptura de la urdimbre durante el tejido de telas (Technometrics, 1982: 63), se sometieron a prueba 100 muestras de hilo. Se determinó el número de ciclos de esfuerzo hasta ruptura para cada muestra de hilo y se obtuvieron los datos siguientes:</p>
<pre class="r"><code>hilos &lt;- scan(&quot;datasets/005-hilos.txt&quot;)
hilos</code></pre>
<pre><code>##   [1]  86 146 251 653  98 249 400 292 131 169 175 176  76 264  15 364 195
##  [18] 262  88 264 157 220  42 321 180 198  38  20  61 121 282 224 149 180
##  [35] 325 250 196  90 229 166  38 337  65 151 341  40  40 135 597 246 211
##  [52] 180  93 315 353 571 124 279  81 186 497 182 423 185 229 400 338 290
##  [69] 398  71 246 185 188 568  55  55  61 244  20 284 393 396 203 829 239
##  [86] 236 286 194 277 143 198 264 105 203 124 137 135 350 193 188</code></pre>
<p>Trazamos nuestro histograma:</p>
<pre class="r"><code>hist(hilos, breaks = &#39;Sturges&#39;, right = FALSE)</code></pre>
<p><img src="U1_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Aquí podemos ver que el histograma se alarga demasiado hacia la derecha, mostrando clases con muy pocas observaciones. En este tipo de ocasiones, puede utilizar un histograma basado en densidades, más que en frecuencias. Ello implica obtener anchuras diferentes.</p>
<pre class="r"><code>hist(hilos, breaks = c(0,50, 100,150, 200,400,600,900), right = FALSE)</code></pre>
<p><img src="U1_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Después de determinar las frecuencias y las frecuencias relativas, se calcula la altura de cada rectángulo con la fórmula <span class="math display">\[
altura=\frac{frecuencia\ relativa\ de\ clase}{ancho\ de\ clase}
\]</span></p>
<p>Las alturas del rectángulo resultante en general se conocen como densidades y la escala vertical es la escala de densidades. Esta prescripción también funcionará cuando los anchos de clase son iguales.</p>
<pre class="r"><code>hist(hilos, breaks = c(0,50, 100,150, 200,400,900), right = FALSE)</code></pre>
<p><img src="U1_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
</div>
<div id="medidas-de-tendencia" class="section level2">
<h2>Medidas de tendencia</h2>
<p>Los resúmenes visuales son bastante atractivos y deseables para obtener percepciones o nociones preliminares. Sin embargo, para un mejor análisis es mejor obtener un resumen basado en la interpretación de medidas numéricas. Suponga que un conjunto de observaciones de la forma <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, <span class="math inline">\(x_3\)</span>, donde cada <span class="math inline">\(x_i\)</span>, (la <span class="math inline">\(i\)</span> es solo un indicador o índice, es decir, no tiene valor numérico). ¿Qué es lo que nos importa saber de ellos?</p>
<div id="la-media" class="section level3">
<h3>La media</h3>
<p>La medida más conocida y útil del centro es la <em>media</em> o promedio aritmético del conjunto. Si los números se denotan como <span class="math inline">\(x_i\)</span>, entonces la media se indica como <span class="math inline">\(\bar{x}\)</span>. Se calcula con la siguiente expresión:</p>
<p><span class="math display">\[
\bar{x}=\frac{x_1+x_2+ ... +x_n}{n}=\frac{\sum_{i=1}^n x_i}{n}
\]</span> Podemos escribir el numerador de la expresión informalmente como <span class="math inline">\(\sum x_i\)</span>, entendiendo que la suma incluye todas las observaciones muestrales.</p>
<div id="ejemplo" class="section level4">
<h4>Ejemplo</h4>
<p>Veamos el caso de un proceso de elaboración de calderas de acero. El metal se encuentra sometido a esfuerzo cáustico, el cual causa agrietamientos, cuya longitud se recogió en la siguiente lista:</p>
<pre class="r"><code>grietas &lt;- scan(&quot;datasets/007-caustic.txt&quot;)
grietas</code></pre>
<pre><code>##  [1] 16.1  9.6 24.9 20.4 12.7 21.2 30.2 25.8 18.5 10.3 25.3 14.0 27.1 45.0
## [15] 23.3 24.2 14.6  8.9 32.4 11.8 28.5</code></pre>
<p>Sumemos todos los valores de la lista, y enseguida dividamos entre el número de observaciones.</p>
<p>Lo primero lo logramos con:</p>
<pre class="r"><code>suma &lt;- sum(grietas)
suma</code></pre>
<pre><code>## [1] 444.8</code></pre>
<p>El tamaño muestral se obtiene con:</p>
<pre class="r"><code>observaciones &lt;- length(grietas)
observaciones</code></pre>
<pre><code>## [1] 21</code></pre>
<p>Ahora sí, calculemos la media:</p>
<pre class="r"><code>media &lt;- suma/observaciones
media</code></pre>
<pre><code>## [1] 21.18095</code></pre>
<p>R tiene la función ya predeterminada:</p>
<pre class="r"><code>mean(grietas)</code></pre>
<pre><code>## [1] 21.18095</code></pre>
</div>
<div id="ejercicio" class="section level4">
<h4>Ejercicio</h4>
<p>Trabajemos ahora con otro conjunto de valores:</p>
<pre class="r"><code>m &lt;- scan(&quot;datasets/004-horno.txt&quot;)
m</code></pre>
<pre><code>##  [1]  2.97  4.00  5.20  5.56  5.94  5.98  6.35  6.62  6.72  6.78  6.80
## [12]  6.85  6.94  7.15  7.16  7.23  7.29  7.62  7.62  7.69  7.73  7.87
## [23]  7.93  8.00  8.26  8.29  8.37  8.47  8.54  8.58  8.61  8.67  8.69
## [34]  8.81  9.07  9.27  9.37  9.43  9.52  9.58  9.60  9.76  9.82  9.83
## [45]  9.83  9.84  9.96 10.04 10.21 10.28 10.28 10.30 10.35 10.36 10.40
## [56] 10.49 10.50 10.64 10.95 11.09 11.12 11.21 11.29 11.43 11.62 11.70
## [67] 11.70 12.16 12.19 12.28 12.31 12.62 12.69 12.71 12.91 12.92 13.11
## [78] 13.38 13.42 13.43 13.47 13.60 13.96 14.24 14.35 15.12 15.24 16.06
## [89] 16.90 18.26</code></pre>
<pre class="r"><code>stem(m)</code></pre>
<pre><code>## 
##   The decimal point is at the |
## 
##    2 | 0
##    4 | 0269
##    6 | 046788992223667799
##    8 | 03345566778134456688888
##   10 | 002333444556011234677
##   12 | 223367799144456
##   14 | 02412
##   16 | 19
##   18 | 3</code></pre>
<pre class="r"><code>mean(m)</code></pre>
<pre><code>## [1] 10.03844</code></pre>
<p>Por lo anterior, podemos entender la media como una especie de balanza o punto de apoyo que nos permite equilibrar los pesos (las observaciones) en un eje horizontal. Ahora bien, este concepto tiene un gran problema: es muy sensible a valores extremos. Por ejemplo, consideremos el conjunto de temperaturas del <em>Challenger</em>:</p>
<pre class="r"><code>temp &lt;- scan(&quot;datasets/001-challenger.txt&quot;)
temp</code></pre>
<pre><code>##  [1] 84 49 61 40 83 67 45 66 70 69 80 58 68 60 67 72 73 70 57 63 70 78 52
## [24] 67 53 67 75 61 70 81 76 79 75 76 58 31</code></pre>
<p>Como ya habíamos visto, la media resultaba ser:</p>
<pre class="r"><code>mean(temp)</code></pre>
<pre><code>## [1] 65.86111</code></pre>
<p>Pero si agregamos un dato muy <em>extraño</em> o no esperado, aún más que el propio 31, como por ejemplo un catastrófico 350:</p>
<pre class="r"><code>n.media &lt;- (sum(temp)+350)/(length(temp)+1)
n.media</code></pre>
<pre><code>## [1] 73.54054</code></pre>
<p>Nuestra media se recorre demasiado hacia la derecha del conjunto, muy cerca del final de los datos, con el afán de «equilibrarlos». Cuando se trabaja con observaciones que pueden tener muchos datos extremos, es recomendable no elegir la media para representar su tendencia. En su lugar, se recomienda la <strong>mediana</strong>.</p>
</div>
</div>
<div id="la-mediana" class="section level3">
<h3>La mediana</h3>
<p>La mediana es una medida de tendencia que literalmente, parte al conjunto de observaciones (previamente ordenadas de menor a mayor) por la mitad. Es decir, es el valor de en medio. Se denota por <span class="math inline">\(\tilde x\)</span>. La mediana se obtiene de dos maneras, dependiendo del número de observaciones <span class="math inline">\(n\)</span>.</p>
<blockquote>
<p>Si el número de observaciones es impar, la mediana es el valor que se encuentra en la siguiente posición:</p>
</blockquote>
<p><span class="math display">\[
\tilde x=valor\ en\ el\ lugar\  \#  \frac{n+1}{2} \ ordenado
\]</span></p>
<blockquote>
<p>Si es par, debemos localizar los dos valores centrales y calcular su media; el resultado es la mediana.</p>
</blockquote>
<p><span class="math display">\[
\tilde x=promedio\ de\ los \ valores\   \#  \frac{n}{2}\ y\ el\ \# \frac{n}{2}+1 \ ordenados
\]</span></p>
<div id="ejemplo-1" class="section level4">
<h4>Ejemplo</h4>
<p>El riesgo de desarrollar deficiencia de hierro es especialmente alto durante el embarazo. El problema con la detección de tal deficiencia es que algunos métodos para determinar el estado del hierro pueden ser afectados por el estado de gravidez mismo. Considérense las siguientes observaciones de concentración de receptores de transferrina de una muestra de mujeres con evidencia de laboratorio de anemia por deficiencia de hierro evidente (“Serum Transferrin Receptor for the Detection of Iron Deficiency in Pregnancy”, Amer. J. of Clinical Nutrition, 1991: 1077-1081):</p>
<pre class="r"><code>Fe &lt;- scan(&quot;datasets/008-hierro.txt&quot;)
Fe</code></pre>
<pre><code>##  [1] 11.9  9.4  8.3  7.6  9.7 20.4 11.5  9.4 15.2 10.4 16.2  9.3</code></pre>
<p>Lo primero que debemos hacer es ordenar los datos de menor a mayor. Lo conseguimos en <em>R</em> con lo siguiente:</p>
<pre class="r"><code>orden &lt;- sort(Fe)
orden</code></pre>
<pre><code>##  [1]  7.6  8.3  9.3  9.4  9.4  9.7 10.4 11.5 11.9 15.2 16.2 20.4</code></pre>
<p>Ahora contamos el total de observaciones:</p>
<pre class="r"><code>n &lt;- length(orden)
n</code></pre>
<pre><code>## [1] 12</code></pre>
<p>Obtengamos la mediana, tomando en cuenta que tenemos un número par de observaciones:</p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
